# Generated by Django 3.0 on 2021-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0010_profile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(default='cv1.html', max_length=250),
        ),
    ]
